jQuery(document).ready(function(){
    var scripts = document.getElementsByTagName("script");
    var jsFolder = "";
    for (var i= 0; i< scripts.length; i++)
    {
        if( scripts[i].src && scripts[i].src.match(/initslider-1\.js/i))
            jsFolder = scripts[i].src.substr(0, scripts[i].src.lastIndexOf("/") + 1);
    }
    jQuery("#amazingslider-1").amazingslider({
        jsfolder:jsFolder,
        width:722,
        height:270,
        skinsfoldername:"skin",
        loadimageondemand:false,
        isresponsive:false,
        autoplayvideo:false,
        pauseonmouseover:true,
        addmargin:false,
        randomplay:false,
        slideinterval:3000,
        enabletouchswipe:true,
        transitiononfirstslide:false,
        loop:0,
        autoplay:true,
        navplayvideoimage:"play-32-32-0.png",
        navpreviewheight:60,
        timerheight:1,
        shownumbering:false,
        skin:"Highlight",
        textautohide:true,
        addgooglefonts:false,
        navshowplaypause:true,
        navshowplayvideo:false,
        navshowplaypausestandalonemarginx:8,
        navshowplaypausestandalonemarginy:8,
        navbuttonradius:0,
        navthumbnavigationarrowimageheight:32,
        navpreviewarrowheight:16,
        showshadow:true,
        navfeaturedarrowimagewidth:8,
        navpreviewwidth:120,
        googlefonts:"Inder",
        textpositionmarginright:24,
        bordercolor: "#fff",
        navthumbnavigationarrowimagewidth:32,
        navthumbtitlehovercss:"text-decoration:none;",
        arrowwidth:32,
        texteffecteasing:"easeOutCubic",
        texteffect:"slide",
        navspacing:2,
        navarrowimage:"navarrows-28-28-0.png",
        ribbonimage:"ribbon_topleft-0.png",
        navwidth:90,
        showribbon:false,
        arrowtop:50,
        timeropacity:0.6,
        navthumbnavigationarrowimage:"carouselarrows-32-32-1.png",
        navshowplaypausestandalone:false,
        navpreviewbordercolor:"#fff",
        ribbonposition:"topleft",
        navthumbdescriptioncss:"display:none;position:relative;padding:2px 4px;text-align:left;font:normal 12px Arial,Helvetica,sans-serif;color:#2d2d2d;",
        navborder:2,
        navthumbtitleheight:18,
        textpositionmargintop:24,
        navswitchonmouseover:false,
        playvideoimage:"playvideo-64-64-0.png",
        arrowimage:"arrows-32-32-0.png",
        textstyle:"static",
        playvideoimageheight:0,
        navfonthighlightcolor:"#666",
        showbackgroundimage:false,
        navpreviewborder:4,
        navopacity:0.8,
        shadowcolor: "#6c6d6d",
        navbuttonshowbgimage:true,
        navbuttonbgimage:"navbuttonbgimage-28-28-0.png",
        textbgcss:"display:block; position:absolute; top:0px; left:0px; width:100%; height:100%; background-color:#333333; opacity:0.8; filter:alpha(opacity=60);",
        playvideoimagewidth:0,
        bottomshadowimagewidth:110,
        showtimer:false,
        navradius:0,
        navshowpreview:false,
        navmarginy:16,
        navmarginx:20,
        navfeaturedarrowimage:"featuredarrow-8-16-0.png",
        navfeaturedarrowimageheight:16,
        navstyle:"thumbnails",
        textpositionmarginleft:24,
        descriptioncss:"display:block; position:relative; margin-top:4px; font:12px Arial,Tahoma,Helvetica,sans-serif; color:#fff;",
        navplaypauseimage:"navplaypause-28-28-0.png",
        backgroundimagetop:-10,
        arrowstyle:"mouseover",
        timercolor:"#ffffff",
        numberingformat:"%NUM/%TOTAL ",
        navfontsize:12,
        navhighlightcolor:"#333333",
        navimage:"bullet-24-24-5.png",
        navheight:66,
        navshowplaypausestandaloneautohide:false,
        navbuttoncolor:"#999999",
        navshowarrow:true,
        navshowfeaturedarrow:true,
        titlecss:"display:block; position:relative; font: 14px Arial,Tahoma,Helvetica,sans-serif; color:#fff;",
        ribbonimagey:0,
        ribbonimagex:0,
        navshowplaypausestandaloneposition:"bottomright",
        shadowsize:8,
        arrowhideonmouseleave:800,
        navshowplaypausestandalonewidth:28,
        navshowplaypausestandaloneheight:28,
        backgroundimagewidth:120,
        navcolor:"#999999",
        navthumbtitlewidth:165,
        navpreviewposition:"left",
        arrowheight:32,
        arrowmargin:5,
        texteffectduration:1000,
        bottomshadowimage:"bottomshadow-110-95-4.png",
        border: 2,
        timerposition:"bottom",
        navfontcolor:"#333",
        navthumbnavigationstyle:"auto",
        borderradius:2,
        navbuttonhighlightcolor:"#333",
        textpositionstatic:"bottom",
        navthumbstyle:"imageandtitledescription",
        textcss:"display:block; padding:12px; text-align:left;",
        navbordercolor: "#d1efff",
        navpreviewarrowimage:"previewarrow-8-16-0.png",
        showbottomshadow:false,
        navdirection:"vertical",
        textpositionmarginstatic:0,
        backgroundimage:"",
        navposition:"right",
        navpreviewarrowwidth:8,
        bottomshadowimagetop:95,
        textpositiondynamic:"bottomleft",
        navshowbuttons:false,
        navthumbtitlecss: "display:block;position:relative;padding:8px 4px;text-align:center;font:bold 12px Arial,Helvetica,sans-serif;color:#454545;line-height:18px",
        textpositionmarginbottom:24,
        slice: {
            duration:500,
            easing:"easeOutCubic",
            checked:true,
            effects:"up,down,updown",
            slicecount:10
        },
        crossfade: {
            duration:500,
            easing:"easeOutCubic",
            checked:true
        },
        fade: {
            duration:500,
            easing:"easeOutCubic",
            checked:true
        },
        transition:"slice,crossfade,fade"
    });
});